# Generated by Django 5.0.2 on 2024-02-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
