# Generated by Django 5.0.2 on 2024-02-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='earlyaccess',
            field=models.BooleanField(default=False),
        ),
    ]
