# Generated by Django 5.0.2 on 2024-02-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_game_demo_game_earlyaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='trailer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='twitter',
            field=models.CharField(default='', max_length=100),
        ),
    ]
