# Generated by Django 5.0.2 on 2024-03-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_game_epic_alter_game_facebook_alter_game_gog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='release',
            new_name='release_window',
        ),
        migrations.AddField(
            model_name='game',
            name='kickstarter_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='kickstarter_page',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='kickstarter_upcoming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(default=''),
        ),
    ]
