# Generated by Django 5.0.2 on 2024-03-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_release_game_release_window_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
