# Generated by Django 5.0.2 on 2024-03-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_game_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='release',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
    ]
