# Generated by Django 5.0.2 on 2024-03-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_release_window_game_release'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='release',
            new_name='release_window',
        ),
    ]
