# Generated by Django 5.0.2 on 2024-03-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_release_game_release_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discord',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
