# Generated by Django 5.0.2 on 2024-03-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_game_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='game',
            name='release_window',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
