# Generated by Django 5.0.2 on 2024-03-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_game_thumbnail_alter_game_release_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_window',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
