# Generated by Django 5.0.2 on 2024-03-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_game_kickstarter_live_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, default=''),
        ),
    ]
